server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false

profile:
  users[0].name: "insurer"
  users[0].organization: "AXA"
  users[0].role: "insurer"